//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace LiveLights {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class Sirens {
        
        private SirensItem[] itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Item")]
        public SirensItem[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItem {
        
        private SirensItemID idField;
        
        private string nameField;
        
        private SirensItemTimeMultiplier timeMultiplierField;
        
        private SirensItemLightFalloffMax lightFalloffMaxField;
        
        private SirensItemLightFalloffExponent lightFalloffExponentField;
        
        private SirensItemLightInnerConeAngle lightInnerConeAngleField;
        
        private SirensItemLightOuterConeAngle lightOuterConeAngleField;
        
        private SirensItemLightOffset lightOffsetField;
        
        private string textureNameField;
        
        private SirensItemSequencerBpm sequencerBpmField;
        
        private SirensItemLeftHeadLight leftHeadLightField;
        
        private SirensItemRightHeadLight rightHeadLightField;
        
        private SirensItemLeftTailLight leftTailLightField;
        
        private SirensItemRightTailLight rightTailLightField;
        
        private SirensItemLeftHeadLightMultiples leftHeadLightMultiplesField;
        
        private SirensItemRightHeadLightMultiples rightHeadLightMultiplesField;
        
        private SirensItemLeftTailLightMultiples leftTailLightMultiplesField;
        
        private SirensItemRightTailLightMultiples rightTailLightMultiplesField;
        
        private SirensItemUseRealLights useRealLightsField;
        
        private SirensItemItem[] sirensField;
        
        public SirensItem() {
            this.textureNameField = "VehicleLight_sirenlight";
        }
        
        /// <remarks/>
        public SirensItemID id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemTimeMultiplier timeMultiplier {
            get {
                return this.timeMultiplierField;
            }
            set {
                this.timeMultiplierField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemLightFalloffMax lightFalloffMax {
            get {
                return this.lightFalloffMaxField;
            }
            set {
                this.lightFalloffMaxField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemLightFalloffExponent lightFalloffExponent {
            get {
                return this.lightFalloffExponentField;
            }
            set {
                this.lightFalloffExponentField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemLightInnerConeAngle lightInnerConeAngle {
            get {
                return this.lightInnerConeAngleField;
            }
            set {
                this.lightInnerConeAngleField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemLightOuterConeAngle lightOuterConeAngle {
            get {
                return this.lightOuterConeAngleField;
            }
            set {
                this.lightOuterConeAngleField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemLightOffset lightOffset {
            get {
                return this.lightOffsetField;
            }
            set {
                this.lightOffsetField = value;
            }
        }
        
        /// <remarks/>
        public string textureName {
            get {
                return this.textureNameField;
            }
            set {
                this.textureNameField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemSequencerBpm sequencerBpm {
            get {
                return this.sequencerBpmField;
            }
            set {
                this.sequencerBpmField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemLeftHeadLight leftHeadLight {
            get {
                return this.leftHeadLightField;
            }
            set {
                this.leftHeadLightField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemRightHeadLight rightHeadLight {
            get {
                return this.rightHeadLightField;
            }
            set {
                this.rightHeadLightField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemLeftTailLight leftTailLight {
            get {
                return this.leftTailLightField;
            }
            set {
                this.leftTailLightField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemRightTailLight rightTailLight {
            get {
                return this.rightTailLightField;
            }
            set {
                this.rightTailLightField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemLeftHeadLightMultiples leftHeadLightMultiples {
            get {
                return this.leftHeadLightMultiplesField;
            }
            set {
                this.leftHeadLightMultiplesField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemRightHeadLightMultiples rightHeadLightMultiples {
            get {
                return this.rightHeadLightMultiplesField;
            }
            set {
                this.rightHeadLightMultiplesField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemLeftTailLightMultiples leftTailLightMultiples {
            get {
                return this.leftTailLightMultiplesField;
            }
            set {
                this.leftTailLightMultiplesField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemRightTailLightMultiples rightTailLightMultiples {
            get {
                return this.rightTailLightMultiplesField;
            }
            set {
                this.rightTailLightMultiplesField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemUseRealLights useRealLights {
            get {
                return this.useRealLightsField;
            }
            set {
                this.useRealLightsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable=false)]
        public SirensItemItem[] sirens {
            get {
                return this.sirensField;
            }
            set {
                this.sirensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemID {
        
        private uint valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemTimeMultiplier {
        
        private decimal valueField;
        
        public SirensItemTimeMultiplier() {
            this.valueField = ((decimal)(1.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "1.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLightFalloffMax {
        
        private decimal valueField;
        
        public SirensItemLightFalloffMax() {
            this.valueField = ((decimal)(10.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "10.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLightFalloffExponent {
        
        private decimal valueField;
        
        public SirensItemLightFalloffExponent() {
            this.valueField = ((decimal)(10.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "10.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLightInnerConeAngle {
        
        private decimal valueField;
        
        public SirensItemLightInnerConeAngle() {
            this.valueField = ((decimal)(3.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "3.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLightOuterConeAngle {
        
        private decimal valueField;
        
        public SirensItemLightOuterConeAngle() {
            this.valueField = ((decimal)(70.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "70.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLightOffset {
        
        private decimal valueField;
        
        public SirensItemLightOffset() {
            this.valueField = ((decimal)(0.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemSequencerBpm {
        
        private uint valueField;
        
        public SirensItemSequencerBpm() {
            this.valueField = ((uint)(200));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "200")]
        public uint value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLeftHeadLight {
        
        private SirensItemLeftHeadLightSequencer sequencerField;
        
        /// <remarks/>
        public SirensItemLeftHeadLightSequencer sequencer {
            get {
                return this.sequencerField;
            }
            set {
                this.sequencerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLeftHeadLightSequencer {
        
        private uint valueField;
        
        public SirensItemLeftHeadLightSequencer() {
            this.valueField = ((uint)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemRightHeadLight {
        
        private SirensItemRightHeadLightSequencer sequencerField;
        
        /// <remarks/>
        public SirensItemRightHeadLightSequencer sequencer {
            get {
                return this.sequencerField;
            }
            set {
                this.sequencerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemRightHeadLightSequencer {
        
        private uint valueField;
        
        public SirensItemRightHeadLightSequencer() {
            this.valueField = ((uint)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLeftTailLight {
        
        private SirensItemLeftTailLightSequencer sequencerField;
        
        /// <remarks/>
        public SirensItemLeftTailLightSequencer sequencer {
            get {
                return this.sequencerField;
            }
            set {
                this.sequencerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLeftTailLightSequencer {
        
        private uint valueField;
        
        public SirensItemLeftTailLightSequencer() {
            this.valueField = ((uint)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemRightTailLight {
        
        private SirensItemRightTailLightSequencer sequencerField;
        
        /// <remarks/>
        public SirensItemRightTailLightSequencer sequencer {
            get {
                return this.sequencerField;
            }
            set {
                this.sequencerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemRightTailLightSequencer {
        
        private uint valueField;
        
        public SirensItemRightTailLightSequencer() {
            this.valueField = ((uint)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLeftHeadLightMultiples {
        
        private byte valueField;
        
        public SirensItemLeftHeadLightMultiples() {
            this.valueField = ((byte)(1));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "1")]
        public byte value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemRightHeadLightMultiples {
        
        private byte valueField;
        
        public SirensItemRightHeadLightMultiples() {
            this.valueField = ((byte)(1));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "1")]
        public byte value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemLeftTailLightMultiples {
        
        private byte valueField;
        
        public SirensItemLeftTailLightMultiples() {
            this.valueField = ((byte)(2));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "2")]
        public byte value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemRightTailLightMultiples {
        
        private byte valueField;
        
        public SirensItemRightTailLightMultiples() {
            this.valueField = ((byte)(2));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "2")]
        public byte value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemUseRealLights {
        
        private bool valueField;
        
        public SirensItemUseRealLights() {
            this.valueField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItem {
        
        private SirensItemItemRotation rotationField;
        
        private SirensItemItemFlashiness flashinessField;
        
        private SirensItemItemCorona coronaField;
        
        private SirensItemItemColor colorField;
        
        private SirensItemItemIntensity intensityField;
        
        private SirensItemItemLightGroup lightGroupField;
        
        private SirensItemItemRotate rotateField;
        
        private SirensItemItemScale scaleField;
        
        private SirensItemItemScaleFactor scaleFactorField;
        
        private SirensItemItemFlash flashField;
        
        private SirensItemItemLight lightField;
        
        private SirensItemItemSpotLight spotLightField;
        
        private SirensItemItemCastShadows castShadowsField;
        
        /// <remarks/>
        public SirensItemItemRotation rotation {
            get {
                return this.rotationField;
            }
            set {
                this.rotationField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemFlashiness flashiness {
            get {
                return this.flashinessField;
            }
            set {
                this.flashinessField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemCorona corona {
            get {
                return this.coronaField;
            }
            set {
                this.coronaField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemColor color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemIntensity intensity {
            get {
                return this.intensityField;
            }
            set {
                this.intensityField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemLightGroup lightGroup {
            get {
                return this.lightGroupField;
            }
            set {
                this.lightGroupField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemRotate rotate {
            get {
                return this.rotateField;
            }
            set {
                this.rotateField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemScale scale {
            get {
                return this.scaleField;
            }
            set {
                this.scaleField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemScaleFactor scaleFactor {
            get {
                return this.scaleFactorField;
            }
            set {
                this.scaleFactorField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemFlash flash {
            get {
                return this.flashField;
            }
            set {
                this.flashField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemLight light {
            get {
                return this.lightField;
            }
            set {
                this.lightField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemSpotLight spotLight {
            get {
                return this.spotLightField;
            }
            set {
                this.spotLightField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemCastShadows castShadows {
            get {
                return this.castShadowsField;
            }
            set {
                this.castShadowsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemRotation {
        
        private SirensItemItemRotationDelta deltaField;
        
        private SirensItemItemRotationStart startField;
        
        private SirensItemItemRotationSpeed speedField;
        
        private SirensItemItemRotationSequencer sequencerField;
        
        private SirensItemItemRotationMultiples multiplesField;
        
        private SirensItemItemRotationDirection directionField;
        
        private SirensItemItemRotationSyncToBpm syncToBpmField;
        
        /// <remarks/>
        public SirensItemItemRotationDelta delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemRotationStart start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemRotationSpeed speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemRotationSequencer sequencer {
            get {
                return this.sequencerField;
            }
            set {
                this.sequencerField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemRotationMultiples multiples {
            get {
                return this.multiplesField;
            }
            set {
                this.multiplesField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemRotationDirection direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemRotationSyncToBpm syncToBpm {
            get {
                return this.syncToBpmField;
            }
            set {
                this.syncToBpmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemRotationDelta {
        
        private decimal valueField;
        
        public SirensItemItemRotationDelta() {
            this.valueField = ((decimal)(0.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemRotationStart {
        
        private decimal valueField;
        
        public SirensItemItemRotationStart() {
            this.valueField = ((decimal)(0.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemRotationSpeed {
        
        private decimal valueField;
        
        public SirensItemItemRotationSpeed() {
            this.valueField = ((decimal)(0.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemRotationSequencer {
        
        private uint valueField;
        
        public SirensItemItemRotationSequencer() {
            this.valueField = ((uint)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemRotationMultiples {
        
        private byte valueField;
        
        public SirensItemItemRotationMultiples() {
            this.valueField = ((byte)(1));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "1")]
        public byte value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemRotationDirection {
        
        private bool valueField;
        
        public SirensItemItemRotationDirection() {
            this.valueField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemRotationSyncToBpm {
        
        private bool valueField;
        
        public SirensItemItemRotationSyncToBpm() {
            this.valueField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemFlashiness {
        
        private SirensItemItemFlashinessDelta deltaField;
        
        private SirensItemItemFlashinessStart startField;
        
        private SirensItemItemFlashinessSpeed speedField;
        
        private SirensItemItemFlashinessSequencer sequencerField;
        
        private SirensItemItemFlashinessMultiples multiplesField;
        
        private SirensItemItemFlashinessDirection directionField;
        
        private SirensItemItemFlashinessSyncToBpm syncToBpmField;
        
        /// <remarks/>
        public SirensItemItemFlashinessDelta delta {
            get {
                return this.deltaField;
            }
            set {
                this.deltaField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemFlashinessStart start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemFlashinessSpeed speed {
            get {
                return this.speedField;
            }
            set {
                this.speedField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemFlashinessSequencer sequencer {
            get {
                return this.sequencerField;
            }
            set {
                this.sequencerField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemFlashinessMultiples multiples {
            get {
                return this.multiplesField;
            }
            set {
                this.multiplesField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemFlashinessDirection direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemFlashinessSyncToBpm syncToBpm {
            get {
                return this.syncToBpmField;
            }
            set {
                this.syncToBpmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemFlashinessDelta {
        
        private decimal valueField;
        
        public SirensItemItemFlashinessDelta() {
            this.valueField = ((decimal)(0.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemFlashinessStart {
        
        private decimal valueField;
        
        public SirensItemItemFlashinessStart() {
            this.valueField = ((decimal)(0.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemFlashinessSpeed {
        
        private decimal valueField;
        
        public SirensItemItemFlashinessSpeed() {
            this.valueField = ((decimal)(0.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemFlashinessSequencer {
        
        private uint valueField;
        
        public SirensItemItemFlashinessSequencer() {
            this.valueField = ((uint)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(uint), "0")]
        public uint value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemFlashinessMultiples {
        
        private byte valueField;
        
        public SirensItemItemFlashinessMultiples() {
            this.valueField = ((byte)(1));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "1")]
        public byte value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemFlashinessDirection {
        
        private bool valueField;
        
        public SirensItemItemFlashinessDirection() {
            this.valueField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemFlashinessSyncToBpm {
        
        private bool valueField;
        
        public SirensItemItemFlashinessSyncToBpm() {
            this.valueField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemCorona {
        
        private SirensItemItemCoronaIntensity intensityField;
        
        private SirensItemItemCoronaSize sizeField;
        
        private SirensItemItemCoronaPull pullField;
        
        private SirensItemItemCoronaFaceCamera faceCameraField;
        
        /// <remarks/>
        public SirensItemItemCoronaIntensity intensity {
            get {
                return this.intensityField;
            }
            set {
                this.intensityField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemCoronaSize size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemCoronaPull pull {
            get {
                return this.pullField;
            }
            set {
                this.pullField = value;
            }
        }
        
        /// <remarks/>
        public SirensItemItemCoronaFaceCamera faceCamera {
            get {
                return this.faceCameraField;
            }
            set {
                this.faceCameraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemCoronaIntensity {
        
        private decimal valueField;
        
        public SirensItemItemCoronaIntensity() {
            this.valueField = ((decimal)(10.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "10.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemCoronaSize {
        
        private decimal valueField;
        
        public SirensItemItemCoronaSize() {
            this.valueField = ((decimal)(1.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "1.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemCoronaPull {
        
        private decimal valueField;
        
        public SirensItemItemCoronaPull() {
            this.valueField = ((decimal)(0.2m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "0.2")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemCoronaFaceCamera {
        
        private bool valueField;
        
        public SirensItemItemCoronaFaceCamera() {
            this.valueField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemColor {
        
        private string valueField;
        
        public SirensItemItemColor() {
            this.valueField = "0xFFFFFF00";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("0xFFFFFF00")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemIntensity {
        
        private decimal valueField;
        
        public SirensItemItemIntensity() {
            this.valueField = ((decimal)(1.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(decimal), "1.0")]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemLightGroup {
        
        private byte valueField;
        
        public SirensItemItemLightGroup() {
            this.valueField = ((byte)(0));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "0")]
        public byte value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemRotate {
        
        private bool valueField;
        
        public SirensItemItemRotate() {
            this.valueField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemScale {
        
        private bool valueField;
        
        public SirensItemItemScale() {
            this.valueField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemScaleFactor {
        
        private byte valueField;
        
        public SirensItemItemScaleFactor() {
            this.valueField = ((byte)(2));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(typeof(byte), "2")]
        public byte value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemFlash {
        
        private bool valueField;
        
        public SirensItemItemFlash() {
            this.valueField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemLight {
        
        private bool valueField;
        
        public SirensItemItemLight() {
            this.valueField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemSpotLight {
        
        private bool valueField;
        
        public SirensItemItemSpotLight() {
            this.valueField = true;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SirensItemItemCastShadows {
        
        private bool valueField;
        
        public SirensItemItemCastShadows() {
            this.valueField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
